export const ACOUNT_BEGIN = "ACOUNT_BEGIN";
export const ACOUNT_EXITO = "ACOUNT_EXITO";
export const ERROR_ACCOUNT = "ERROR_ACCOUNT";
export const CONFIRM_ACCOUNT_BEGIN = "CONFIRM_ACCOUNT_BEGIN";
export const CONFIRM_ACCOUNT_EXITO = "CONFIRM_ACCOUNT_EXITO";
export const LIMPIAR = "LIMPIAR";
export const USER_SUGGESTION = "USER_SUGGESTION";

export const RESEND_EMAIL = "RESEND_EMAIL";
export const RECOVERY_PAS_ERROR = "RECOVERY_PAS_ERROR";
export const RECOVERY_PAS_SUCCESS = "RECOVERY_PAS_SUCCES";

//Login
export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const GET_USERINFO = "OBTENEGET_USERINFOR_USUARIO";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGON = "LOGON";
export const LIMPIAR_USER = "LIMPIAR_USER";

//Genericos
export const BEGIN = "BEGIN";
export const EXITO = "EXITO";
export const ERROR = "ERROR";
export const MENU_OPTION = "MENU_OPTION";
